
[package]
name = "processor"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25", default-features = false, features = ["jpeg"] }
jpeg-encoder = "0.6"
aws-config = "1"
aws-sdk-s3 = "1"
aws_lambda_events = { version = "0.15", default-features = false, features = ["sqs"] }
lambda_runtime = "0.13"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
